# Generated by Django 2.2.18 on 2021-02-19 14:41

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('integrated_channel', '0002_learnerdatatransmissionaudit_subsection_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contentmetadataitemtransmission',
            name='channel_metadata',
            field=jsonfield.fields.JSONField(),
        ),
    ]
